local colors = {
  {name="cherry rose", hex="#ab274f"},
  {name="molten lava", hex="#7c0902"},
  {name="vibrant coral", hex="#fe6f5e"},
  {name="blushed brick", hex="#bf4f51"},
  {name="dark garnet", hex="#660000"},
  {name="bubblegum pink", hex="#fb607f"},
  {name="burgundy", hex="#800020"},
  {name="electric red", hex="#ff0800"},
  {name="powder blush", hex="#fdbcb4"},
  {name="intense cherry", hex="#c51e3a"},
  {name="deep crimson", hex="#960018"},
  {name="magenta bloom", hex="#de3163"},
  {name="burnt tangerine", hex="#e23d28"},
  {name="night bordeaux", hex="#58111a"},
  {name="fiery terracotta", hex="#e44d2e"},
  {name="dark amaranth", hex="#7f1734"},
  {name="blazing flame", hex="#ff3800"},
  {name="sweet salmon", hex="#f88379"},
  {name="burnt rose", hex="#893f45"},
  {name="mahogany red", hex="#b31b1b"},
  {name="classic crimson", hex="#dc143c"},
  {name="blood red", hex="#8b0000"},
  {name="dark wine", hex="#801818"},
  {name="brick red", hex="#b22222"},
  {name="flag red", hex="#ce2029"},
  {name="hot fuchsia", hex="#ff004f"},
  {name="bitter chocolate", hex="#733635"},
  {name="strawberry red", hex="#ed2939"},
  {name="lobster pink", hex="#cd5c5c"},
  {name="rosy copper", hex="#d05340"},
  {name="light coral", hex="#f08080"},
  {name="grapefruit pink", hex="#ff7f7f"},
  {name="ruby red", hex="#a50021"},
  {name="burnt orange", hex="#c04000"},
  {name="maroon", hex="#800000"},
      {name="soft blush", hex="#ffe4e1"},
  {name="pure red", hex="#fe0000"},
  {name="dusty rose", hex="#c08081"},
  {name="crushed berry", hex="#841617"},
  {name="oxblood", hex="#990000"},
  {name="tomato jam", hex="#cc3333"},
  {name="pastel pink", hex="#ffc0cb"},
  {name="scarlet rush", hex="#dc343b"},
  {name="red", hex="#ff0000"},
  {name="brown red", hex="#a52a2a"},
  {name="racing red", hex="#ed1b24"},
  {name="watermelon", hex="#ee204e"},
  {name="lipstick red", hex="#f2003c"},
  {name="carmine", hex="#c40234"},
  {name="punch red", hex="#ed2839"},
  {name="primary scarlet", hex="#e60026"},
  {name="neon pink", hex="#ff0080"},
  {name="chocolate plum", hex="#674846"},
  {name="rosewood", hex="#c21e56"},
  {name="smoky rose", hex="#905d5d"},
  {name="dusty mauve", hex="#ab4e52"},
  {name="black cherry", hex="#65000b"},
  {name="rosy taupe", hex="#bc8f8f"},
  {name="rusty spice", hex="#b7410e"},
  {name="raspberry", hex="#da2c43"},
  {name="salmon", hex="#fa8072"},
  {name="cotton candy", hex="#ff91a4"},
  {name="scarlet fire", hex="#ff2400"},
  {name="spicy orange", hex="#d44500"},
  {name="cotton rose", hex="#f4c2c2"},
  {name="tomato", hex="#ff6347"},
  {name="inferno", hex="#a91101"},
  {name="cinnabar", hex="#e34234"},
  {name="wine plum", hex="#722f37"},
  {name="flame orange", hex="#ff4f00"},
  {name="burnt caramel", hex="#c46210"},
  {name="amber gold", hex="#ffbf00"},
  {name="peach fuzz", hex="#fbceb1"},
  {name="tangerine dream", hex="#ff9966"},
  {name="chocolate brown", hex="#964b00"},
  {name="autumn ember", hex="#bf5700"},
  {name="golden apricot", hex="#e09540"},
  {name="carrot orange", hex="#ed9121"},
  {name="champagne mist", hex="#f7e7ce"},
  {name="coral glow", hex="#ff7f50"},
  {name="dark orange", hex="#ff8c00"},
  {name="desert sand", hex="#edc9af"},
  {name="brick ember", hex="#ba160c"},
  {name="spicy paprika", hex="#e25822"},
  {name="tiger flame", hex="#fe5a1d"},
  {name="gold", hex="#ffd700"},
  {name="molten orange", hex="#f04a00"},
  {name="goldenrod", hex="#daa520"},
  {name="honey bronze", hex="#e8ac41"},
  {name="soft apricot", hex="#fed8b1"},
  {name="atomic tangerine", hex="#ff7538"},
  {name="blaze orange", hex="#ff5800"},
  {name="amber glow", hex="#ffa000"},
  {name="orange", hex="#ffa500"},
  {name="vivid tangerine", hex="#ff8000"},
  {name="papaya whip", hex="#ffefd5"},
  {name="light apricot", hex="#ffe5b4"},
  {name="toasted almond", hex="#d99058"},
  {name="cayenne red", hex="#ec5800"},
  {name="deep saffron", hex="#ff8f00"},
  {name="pumpkin spice", hex="#ff7518"},
  {name="harvest orange", hex="#ff7900"},
  {name="saffron", hex="#f4c430"},
  {name="autumn leaf", hex="#e86100"},
  {name="crimson carrot", hex="#f94d00"},
  {name="tiger orange", hex="#f28500"},
  {name="bronze spice", hex="#cd5700"},
  {name="copperwood", hex="#b56917"},
  {name="princeton orange", hex="#ff8200"},
  {name="sunflower gold", hex="#f1b42f"},
  {name="almond cream", hex="#efdecd"},
  {name="dusty taupe", hex="#9f8170"},
  {name="beige", hex="#f5f5dc"},
  {name="dark coffee", hex="#3d2b1f"},
  {name="rich mahogany", hex="#3d0c02"},
  {name="charcoal brown", hex="#3b3c36"},
  {name="clay soil", hex="#79443b"},
  {name="bone", hex="#e3dac9"},
  {name="bronze", hex="#cd7f32"},
  {name="rust brown", hex="#993300"},
  {name="cinnamon wood", hex="#af6e4d"},
  {name="light bronze", hex="#daa06d"},
  {name="burnt peach", hex="#e97451"},
  {name="chestnut", hex="#8a3324"},
  {name="camel", hex="#c19a6b"},
  {name="espresso", hex="#592720"},
  {name="golden chestnut", hex="#cc7f3b"},
  {name="faded copper", hex="#a0785a"},
  {name="reddish brown", hex="#954535"},
  {name="raw umber", hex="#7b3f00"},
  {name="golden sand", hex="#ddd06a"},
  {name="chocolate", hex="#d2691e"},
  {name="coffee bean", hex="#6f4e37"},
  {name="copper", hex="#b87333"},
  {name="olive wood", hex="#81613e"},
  {name="dark khaki", hex="#4a412a"},
  {name="pale oak", hex="#dac8ae"},
  {name="sunlit clay", hex="#e1a95f"},
  {name="sand", hex="#c2b280"},
  {name="light caramel", hex="#e5aa70"},
  {name="olive bark", hex="#6c541e"},
  {name="amber earth", hex="#e48400"},
  {name="golden earth", hex="#996515"},
  {name="harvest gold", hex="#da9100"},
  {name="khaki beige", hex="#c3b090"},
  {name="brown bark", hex="#6b4423"},
  {name="mauve bark", hex="#674c47"},
  {name="ochre", hex="#cc7722"},
  {name="toffee brown", hex="#926644"},
  {name="terracotta clay", hex="#a45a52"},
  {name="oxidized iron", hex="#a81c07"},
  {name="saddle brown", hex="#80461b"},
  {name="sandy brown", hex="#f4a460"},
  {name="golden bronze", hex="#cba135"},
  {name="dark walnut", hex="#59260b"},
  {name="walnut", hex="#704214"},
  {name="brandy", hex="#882d17"},
  {name="red ochre", hex="#cb410b"},
  {name="tan", hex="#d2b48c"},
  {name="taupe", hex="#483c32"},
  {name="ash brown", hex="#635147"},
  {name="deep mocha", hex="#44362f"},
  {name="stone brown", hex="#5c5248"},
  {name="taupe grey", hex="#645452"},
  {name="wheat", hex="#f5deb3"},
  {name="straw gold", hex="#e9d66b"},
  {name="bright lemon", hex="#fdee00"},
  {name="sandy clay", hex="#e0ab76"},
  {name="sunbeam yellow", hex="#ffef00"},
  {name="lime yellow", hex="#dfff00"},
  {name="golden glow", hex="#e4d00a"},
  {name="ivory mist", hex="#fff8e7"},
  {name="cream", hex="#fffdd0"},
  {name="dark goldenrod", hex="#b8860b"},
  {name="soft fawn", hex="#cdb280"},
  {name="light gold", hex="#eedc82"},
  {name="golden orange", hex="#ef9b0f"},
  {name="metallic gold", hex="#d4af37"},
  {name="amber honey", hex="#e6a817"},
  {name="canary yellow", hex="#fcf75e"},
  {name="ivory", hex="#fffff0"},
  {name="jasmine", hex="#f8de7e"},
  {name="bright amber", hex="#faca16"},
  {name="lemon chiffon", hex="#fffacd"},
  {name="neon chartreuse", hex="#e3ff00"},
  {name="light yellow", hex="#ffffe0"},
  {name="banana cream", hex="#fbec5d"},
  {name="school bus yellow", hex="#ffc40c"},
  {name="lime cream", hex="#e3f988"},
  {name="mustard", hex="#ffdb58"},
  {name="royal gold", hex="#fada5e"},
  {name="navajo white", hex="#ffdead"},
  {name="old gold", hex="#cfb53b"},
  {name="olive", hex="#808000"},
  {name="soft peach", hex="#fadfad"},
  {name="lemon lime", hex="#dae231"},
  {name="tuscan sun", hex="#f4c431"},
  {name="bright gold", hex="#ffd800"},
  {name="amber flame", hex="#ffba00"},
  {name="pale amber", hex="#e4d96f"},
  {name="golden pollen", hex="#ffcc33"},
  {name="apricot cream", hex="#fad6a5"},
  {name="vanilla custard", hex="#f3e5ab"},
  {name="yellow", hex="#ffff00"},
  {name="lime moss", hex="#8db600"},
  {name="tropical mint", hex="#00ffbf"},
  {name="sage green", hex="#7ba05b"},
  {name="forest moss", hex="#568203"},
  {name="neon grass", hex="#66ff00"},
  {name="deep forest", hex="#004225"},
  {name="pine teal", hex="#1b4d3e"},
  {name="dark spruce", hex="#1e4d2b"},
  {name="emerald depths", hex="#00563b"},
  {name="celadon", hex="#ace1af"},
  {name="lime flash", hex="#80ff00"},
  {name="cyan", hex="#00ffff"},
  {name="evergreen", hex="#013220"},
  {name="olive leaf", hex="#4a5d23"},
  {name="jade green", hex="#03c03c"},
  {name="turf green", hex="#177245"},
  {name="dark emerald", hex="#00693e"},
  {name="emerald", hex="#50c876"},
  {name="electric green", hex="#00ff40"},
  {name="fern", hex="#4f7942"},
  {name="forest green", hex="#228b22"},
  {name="lime", hex="#00ff00"},
  {name="green yellow", hex="#adff2f"},
  {name="spring laser", hex="#3fff00"},
  {name="honey dew", hex="#f0fff0"},
  {name="deep teal", hex="#49796b"},
  {name="hunter green", hex="#355e3b"},
  {name="india green", hex="#138808"},
  {name="jungle green", hex="#00a86b"},
  {name="seaweed", hex="#29ab87"},
  {name="bright fern", hex="#4cbb17"},
  {name="lawn green", hex="#7cfc00"},
  {name="light green", hex="#90ee90"},
  {name="chartreuse", hex="#c0ff00"},
  {name="lime green", hex="#32cd32"},
  {name="malachite", hex="#0bda51"},
  {name="moss green", hex="#74c365"},
  {name="dark teal", hex="#004953"},
  {name="mint leaf", hex="#3eb489"},
  {name="palm leaf", hex="#8a9a5b"},
  {name="pine blue", hex="#317873"},
  {name="laser green", hex="#39ff14"},
  {name="green", hex="#008000"},
  {name="muted olive", hex="#9ab973"},
  {name="black forest", hex="#00401a"},
  {name="verdigris", hex="#00a693"},
  {name="medium jungle", hex="#00a550"},
  {name="blue spruce", hex="#01796f"},
  {name="willow green", hex="#93c572"},
  {name="dusty olive", hex="#6c7c59"},
  {name="strong cyan", hex="#00cccc"},
  {name="dry sage", hex="#bcb88a"},
  {name="mint glow", hex="#76ff7a"},
  {name="sea green", hex="#2e8b57"},
  {name="radioactive grass", hex="#55dd33"},
  {name="shamrock", hex="#009e60"},
  {name="slime lime", hex="#a7fc00"},
  {name="spring green", hex="#00ff7f"},
  {name="tea green", hex="#d0f0c0"},
  {name="teal", hex="#008080"},
  {name="turquoise", hex="#40d0e0"},
  {name="jungle teal", hex="#40826d"},
  {name="yellow green", hex="#9acd32"},
  {name="alice blue", hex="#f0f8ff"},
  {name="cyan glow", hex="#0fffff"},
  {name="aquamarine", hex="#7fffd4"},
  {name="azure blue", hex="#007fff"},
  {name="azure mist", hex="#f0ffff"},
  {name="blue green", hex="#0d98ba"},
  {name="deep sky blue", hex="#00bfff"},
  {name="stormy teal", hex="#006d6f"},
  {name="icy aqua", hex="#b2ffff"},
  {name="cerulean", hex="#007ba7"},
  {name="dark cyan", hex="#008b8b"},
  {name="electric aqua", hex="#7df9ff"},
  {name="neon ice", hex="#15f4ee"},
  {name="ocean mist", hex="#3ab09e"},
  {name="soft cyan", hex="#99ffff"},
  {name="light cyan", hex="#e0ffff"},
  {name="light sea green", hex="#20b2aa"},
  {name="frozen water", hex="#dffffd"},
  {name="pacific blue", hex="#3aa8c1"},
  {name="turquoise surf", hex="#1ca9c9"},
  {name="bright sky", hex="#00b7eb"},
  {name="deep ocean", hex="#007a74"},
  {name="pearl aqua", hex="#81d8d0"},
  {name="tropical teal", hex="#43b3ae"},
  {name="sky aqua", hex="#00ccff"},
  {name="seagrass", hex="#39a78d"},
  {name="sky surge", hex="#00b9e8"},
  {name="air force blue", hex="#5d8aa8"},
  {name="steel blue", hex="#72a0c1"},
  {name="cool sky", hex="#6cb4ee"},
  {name="bright marine", hex="#0070bb"},
  {name="baby blue", hex="#89cff0"},
  {name="oxford navy", hex="#003262"},
  {name="cornflower ocean", hex="#2072af"},
  {name="brilliant azure", hex="#318ce7"},
  {name="blue", hex="#0000ff"},
  {name="blue grey", hex="#6699cc"},
  {name="bondi blue", hex="#0095b6"},
  {name="digital blue", hex="#0070ff"},
  {name="royal azure", hex="#3457d5"},
  {name="muted teal", hex="#85b09a"},
  {name="sky reflection", hex="#7bafd4"},
  {name="blue bell", hex="#4997d0"},
  {name="sapphire sky", hex="#246bce"},
  {name="blue energy", hex="#468fea"},
  {name="ultrasonic blue", hex="#3b00db"},
  {name="cobalt blue", hex="#0047ab"},
  {name="pale sky", hex="#b9d9eb"},
  {name="cornflower blue", hex="#6495ed"},
  {name="crayola blue", hex="#1f75fe"},
  {name="true azure", hex="#0000b8"},
  {name="twilight indigo", hex="#1f305e"},
  {name="tech blue", hex="#1560bd"},
  {name="dodger blue", hex="#1e90ff"},
  {name="navy electric", hex="#00009c"},
  {name="egyptian blue", hex="#1034a6"},
  {name="deep twilight", hex="#16166b"},
  {name="glaucous", hex="#6082b6"},
  {name="ocean deep", hex="#1164b4"},
  {name="electric indigo", hex="#6f00ff"},
  {name="twitter blue", hex="#0072bb"},
  {name="indigo", hex="#4b0082"},
  {name="yale blue", hex="#00416a"},
  {name="international klein blue", hex="#002fa7"},
  {name="baby blue ice", hex="#8ab9f1"},
  {name="baltic blue", hex="#26619c"},
  {name="light blue", hex="#add8e6"},
  {name="sky blue", hex="#87cefa"},
  {name="majorelle blue", hex="#6050dc"},
  {name="french blue", hex="#2b4593"},
  {name="maya blue", hex="#73c2fb"},
  {name="medium blue", hex="#0000cd"},
  {name="medium slate blue", hex="#7b68ee"},
  {name="midnight blue", hex="#191970"},
  {name="pacific cyan", hex="#0093af"},
  {name="navy", hex="#000080"},
  {name="ocean blue", hex="#0087bd"},
  {name="electric sapphire", hex="#4666ff"},
  {name="frosted blue", hex="#a4dded"},
  {name="prussian blue", hex="#002147"},
  {name="bright indigo", hex="#273be2"},
  {name="frozen lake", hex="#87D3F8"},
  {name="deep navy", hex="#011f5b"},
  {name="peirwinkle", hex="#CCCCFF"},
  {name="persian blue", hex="#1c39bb"},
  {name="electric royal", hex="#000f89"},
  {name="fresh sky", hex="#45b1e8"},
  {name="steel azure", hex="#224c98"},
  {name="powder blue", hex="#9eb9d4"},
  {name="deep space blue", hex="#003153"},
  {name="true cobalt", hex="#002387"},
  {name="full spectrum blue", hex="#2454ff"},
  {name="royal blue", hex="#4169e1"},
  {name="imperial blue", hex="#002366"},
  {name="cool horizon", hex="#76abdf"},
  {name="sapphire", hex="#0f52ba"},
  {name="bright teal blue", hex="#0076b6"},
  {name="slate indigo", hex="#4b61d1"},
  {name="dusty denim", hex="#5d89ba"},
  {name="sky blue (light)", hex="#87ceeb"},
  {name="space indigo", hex="#1e2952"},
  {name="steel blue", hex="#4682b4"},
  {name="laser blue", hex="#0059cf"},
  {name="smart blue", hex="#2d68c4"},
  {name="bright ocean", hex="#3e8ede"},
  {name="rich cerulean", hex="#2774ae"},
  {name="dark ultramarine", hex="#120a8f"},
  {name="cloudy sky", hex="#4b92db"},
  {name="icy blue", hex="#afdbf5"},
  {name="ocean twilight", hex="#324ab2"},
  {name="wisteria blue", hex="#7c9ed9"},
  {name="regal navy", hex="#00356b"},
  {name="dusk blue", hex="#2e5090"},
  {name="vivid royal", hex="#0014a8"},
  {name="amethyst smoke", hex="#b284be"},
  {name="lavender purple", hex="#9966cc"},
  {name="blue violet", hex="#8a2be2"},
  {name="royal plum", hex="#702963"},
  {name="dusty lavender", hex="#856088"},
  {name="midnight violet", hex="#301934"},
  {name="dark violet", hex="#9400d3"},
  {name="mauve shadow", hex="#614051"},
  {name="hyper magenta", hex="#bf00ff"},
  {name="violet ray", hex="#8f00ff"},
  {name="vintage grape", hex="#563c5c"},
  {name="velvet orchid", hex="#6c3082"},
  {name="pastel petal", hex="#f2c1d1"},
  {name="raspberry plum", hex="#b53389"},
  {name="orchid mist", hex="#d473d4"},
  {name="royal violet", hex="#8806ce"},
  {name="magenta", hex="#ff00ff"},
  {name="indigo bloom", hex="#6f2da8"},
  {name="mauve magic", hex="#df73ff"},
  {name="violet twilight", hex="#5a4fcf"},
  {name="blackberry cream", hex="#5b3256"},
  {name="lavender blush", hex="#fff0f5"},
  {name="bright lavender", hex="#b57edc"},
  {name="lavender", hex="#e6e6fa"},
  {name="lilac", hex="#c8a2c8"},
  {name="dark magenta", hex="#880085"},
  {name="mauve", hex="#e0b0ff"},
  {name="royal orchid", hex="#8d029b"},
  {name="dusty mauve", hex="#997a8d"},
  {name="fuchsia plum", hex="#c54b8c"},
  {name="dark raspberry", hex="#8b004b"},
  {name="orchid", hex="#da70d6"},
  {name="deep purple", hex="#682860"},
  {name="lavender veil", hex="#fae6fa"},
  {name="indigo ink", hex="#32127a"},
  {name="neon violet", hex="#df00ff"},
  {name="pink orchid", hex="#dbb2d1"},
  {name="plum", hex="#dda0dd"},
  {name="vintage lavender", hex="#86608e"},
  {name="old rose", hex="#cc8899"},
  {name="purple", hex="#800080"},
  {name="amethyst", hex="#9a4eae"},
  {name="rebecca purple", hex="#663399"},
  {name="deep lilac", hex="#7851a9"},
  {name="medium violet red", hex="#c71585"},
  {name="dark amethyst", hex="#32174d"},
  {name="slate blue", hex="#6a5acd"},
  {name="vivid orchid", hex="#cc33cc"},
  {name="indigo velvet", hex="#512888"},
  {name="thislte", hex="#d8bfd8"},
  {name="soft periwinkle", hex="#9683ec"},
  {name="crimson violet", hex="#66023c"},
  {name="dusty grape", hex="#645394"},
  {name="purple (x11)", hex="#a020f0"},
  {name="ultra violet", hex="#8000ff"},
  {name="wisteria", hex="#c9a0dc"},
  {name="amaranth", hex="#e52b50"},
  {name="cotton candy", hex="#ff91af"},
  {name="dark magenta", hex="#8b008b"},
  {name="velvet purple", hex="#683068"},
  {name="neon fuchsia", hex="#ff1dce"},
  {name="hot rose", hex="#ca1f7b"},
  {name="barbie pink", hex="#ff0090"},
  {name="deep pink", hex="#f653a6"},
  {name="rose punch", hex="#d0417e"},
  {name="berry blush", hex="#9f4576"},
  {name="grape soda", hex="#8e4585"},
  {name="cotton bloom", hex="#fe4eda"},
  {name="vintage berry", hex="#8e3a59"},
  {name="raspberry red", hex="#e30b5c"},
  {name="fuchsia pop", hex="#ff33cc"},
  {name="bubblegum fizz", hex="#ff66cc"},
  {name="lilac ash", hex="#aa98a9"},
  {name="shocking pink", hex="#fc0fc0"},
  {name="bright peony", hex="#ff6fff"},
  {name="petal pink", hex="#cf71af"},
  {name="hot berry", hex="#cf3476"},
  {name="violet", hex="#ee82ee"},
  {name="pink mist", hex="#f19cbb"},
  {name="blush rose", hex="#de5d83"},
  {name="baby pink", hex="#ffa6c9"},
  {name="powder petal", hex="#f1ddcf"},
  {name="cherry blossom", hex="#ffb7c5"},
  {name="rosewood", hex="#a8516e"},
  {name="rose kiss", hex="#f56fa1"},
  {name="deep pink", hex="#ff1493"},
  {name="berry lipstick", hex="#d71868"},
  {name="wild strawberry", hex="#f64a8a"},
  {name="rose wine", hex="#c74375"},
  {name="electric rose", hex="#f400a1"},
  {name="neon rose", hex="#ff00cc"},
  {name="hot pink (web)", hex="#ff69b4"},
  {name="blush pop", hex="#fbaed2"},
  {name="fuchsia flame", hex="#e4007c"},
  {name="petal frost", hex="#ffdae9"},
  {name="soft blossom", hex="#f2bdcd"},
  {name="almond silk", hex="#edcdc2"},
  {name="peach glow", hex="#ffcba4"},
  {name="brilliant rose", hex="#fe28a2"},
  {name="pink carnation", hex="#f77fbe"},
  {name="petal rouge", hex="#ed7a9b"},
  {name="razzmatazz", hex="#e3256b"},
  {name="berry crush", hex="#b3446c"},
  {name="dragonfruit", hex="#f9429e"},
  {name="seashell", hex="#fff5ee"},
  {name="bublegum tint", hex="#fc89ac"},
  {name="sweet peony", hex="#de6fa1"},
  {name="soft linen", hex="#edeae0"},
  {name="platinum", hex="#f2f3f4"},
  {name="antique white", hex="#faebd7"},
  {name="porcelain", hex="#fefefa"},
  {name="cornsilk", hex="#fff8dc"},
  {name="pearl beige", hex="#efdfbb"},
  {name="eggshell", hex="#f0ead6"},
  {name="floral white", hex="#fffaf0"},
  {name="ghost white", hex="#f8f8ff"},
  {name="peachment", hex="#f4f0ec"},
  {name="linen", hex="#faf0e6"},
  {name="lavender mist", hex="#f8f4ff"},
  {name="mint cream", hex="#f5fffa"},
  {name="frosted mint", hex="#e9ffdb"},
  {name="old lace", hex="#fdf5e6"},
  {name="vanilla cream", hex="#f1e8d2"},
  {name="sand dune", hex="#eae0c8"},
  {name="alabaster grey", hex="#e5e4e2"},
  {name="bright snow", hex="#f7f7f7"},
  {name="snow", hex="#fffafa"},
  {name="white", hex="#ffffff"},
  {name="white smoke", hex="#f5f5f5"},
  {name="dust grey", hex="#dbd7d2"},
  {name="silver", hex="#c0c0c0"},
  {name="pale slate", hex="#bebfc5"},
  {name="ash grey", hex="#beb2b5"},
  {name="taupe", hex="#98817b"},
  {name="cool steel", hex="#91a3b0"},
  {name="lavender grey", hex="#8c92ac"},
  {name="rosy granite", hex="#8b8589"},
  {name="grey olive", hex="#848482"},
  {name="grey", hex="#808080"},
  {name="slate grey", hex="#708090"},
  {name="dim grey", hex="#696969"},
  {name="charcoal", hex="#555555"},
  {name="blue slate", hex="#536878"},
  {name="jet black", hex="#2a3439"},
  {name="granite", hex="#4d5d53"},
  {name="dark slate grey", hex="#2f4f4f"},
  {name="black", hex="#000000"},
  {name="deep walnut", hex="#4b3621"},
  {name="charcoal blue", hex="#36454f"},
  {name="ebony", hex="#555d50"},
  {name="carbon black", hex="#1b1b1b"},
  {name="graphite", hex="#343434"},
  {name="coffee bean", hex="#1a1110"},
  {name="onyx", hex="#111111"},
  {name="gunmetal", hex="#353839"},
  {name="iron grey", hex="#414a4c"},
  {name="shadow grey", hex="#242124"},
  {name="ink black", hex="#010b13"},
  {name="pitch black", hex="#100c08"},
}

return colors
