name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Description
        Describe the bug you encountered.

  - type: input
    id: version
    attributes:
      label: Neovim Version
      description: Run `:version` and paste the output
      placeholder: "NVIM v0.11.0-dev-123+g4567890"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      placeholder: "Ubuntu 22.04, macOS 13.0, etc."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the bug
      placeholder: |
        1. Open Neovim with this config
        2. Run `:Lazy sync`
        3. Try to use feature X
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs/Error Messages
      description: Any relevant error messages or logs
      placeholder: |
        ```
        Error message here
        ```
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional information that might be helpful