name: Documentation Issue
description: Report issues with documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        ## Documentation Issue
        Report problems with documentation, missing information, or unclear explanations.

  - type: input
    id: page
    attributes:
      label: Documentation Page
      description: Which documentation page has the issue?
      placeholder: "installation.md, lsp.md, etc."

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What's wrong with the documentation?
      placeholder: "The documentation says X but actually Y happens..."
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Fix
      description: How should the documentation be improved?
      placeholder: "Change X to Y, add section about Z, etc."

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional information